### ISSUE TITLE
[상품] 주문쪽하고 머지 후 카프카관련 테스트

### ISSUE THREAD

**Issue by bongdaehyun** [dev-wonny/coopang#102]
## TODO
* [x] 카프카 설정 테스트해보기
* [x] 에러가 있을 경우 공유하고 고치기..
## 예상 개발 기간
* 24.10. 08~ 24.10.09(일)

**Comment by jiminchur** [comment]
## 수정 사항 1
### 오류 원인
* KafkaListener를 통해 에러가 났음에도 토픽이 사라지지않아 계속 불러오는 현상
### 해결 방법
* ConsumerApplicationKafkaConfig에 아래 코드 추가
```
@Bean
    public DefaultErrorHandler errorHandler(KafkaTemplate<String, String> template) {
        // DeadLetterPublishingRecoverer를 사용하여 실패한 메시지를 DLT로 전송
        DeadLetterPublishingRecoverer recoverer = new DeadLetterPublishingRecoverer(template);
        return new DefaultErrorHandler(recoverer, new FixedBackOff(1000L, 0)); // 1초 대기, 재시도 횟수
    }
```
* DLT로 전송하는 로직 (즉, 쓰레기통으로 들어간다라는 뜻)

**Comment by jiminchur** [comment]
## 수정 사항 2
### 오류 원인
* 네임잉을 설정을 잘못해서 생긴 오류
### 해결 방법
* 네임잉 통일화

**Comment by jiminchur** [comment]
## 수정 사항 3
### 오류 원인
* 임의 PG사 API 호출시 Security에 걸려서 403에러 발생
### 해결 방법
* PG사 요청을 보낼때도 Header에 ID랑 Role추가해서 진행하기

**Comment by bongdaehyun** [comment]
# 수정 사항 4

## 오류 원인
응답 메시지의 데이터를 잘못 설정하여 결제 정보 저장 시 에러 발생
<img width="723" alt="image" src="https://github.com/user-attachments/assets/0ef49255-cd82-4fc1-aac7-319eb8a37db2">

## 해결 방법

메시지 통일화
