### ISSUE TITLE
[주문] 수정된 시나리오에 맞춰서 재수정 진행

### ISSUE THREAD

**Issue by jiminchur** [dev-wonny/coopang#115]
### 결제 실패
* [x] PG사 요청 url 생성하기
### 결제 성공
* [ ] POST - 결제 기록 요청 (payment history)
* [x] POST - 주문 생성 요청 (Order)
* [ ] orderId는 timestamp + userId로 미리 생성한다는걸로 진행
### 재고 감소 요청 - 성공
* [x] 주문 생성시 - 생성완료 200으로 Return
* [x] process_product로 전달
* [x] complete_product로 전달 / 수신 후 주문 상태값 Pending으로 변경
* [x] process_delivery로 전달 (배송 등록)
### 재고 감소 요청 - 실패
* [x] 주문 생성시 - 생성완료 200으로 Return
* [x] process_product로 전달
* [x] error_product로 전달 / 수신 후 주문 상태값 Canceled로 변경
* [x] PG사 결제 취소 요청 
* [x] 결제 기록 테이블에 기록
### 주문 취소 
* [x] 주문 상태값 변경 요청 Canceled로 변경
* [x] 주문 취소 완료 및 추후에 돈은 계좌에 들어간다는 메세지 리턴
* [x] PG사 결제 취소 요청 
* [x] 결제 기록 테이블에 기록
* [x] 재고 rollback_product로 보냄

**Comment by jiminchur** [comment]
## API Test 진행 시 오류
* 수량을 오버해서 요청을 보낼때 수량 부족으로 토픽으로 전달할때 동일한 부분에 대해서 여러번 요청이 됨
![스크린샷 2024-10-10 오후 1 40 35](https://github.com/user-attachments/assets/e9f028ca-e730-4d94-91f9-a240d5af00c5)
@bongdaehyun

**Comment by bongdaehyun** [comment]
> ## API Test 진행 시 오류
> * 수량을 오버해서 요청을 보낼때 수량 부족으로 토픽으로 전달할때 동일한 부분에 대해서 여러번 요청이 됨
>   ![스크린샷 2024-10-10 오후 1 40 35](https://private-user-images.githubusercontent.com/145955453/375219678-e9f028ca-e730-4d94-91f9-a240d5af00c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzY3NTUsIm5iZiI6MTcyODUzNjQ1NSwicGF0aCI6Ii8xNDU5NTU0NTMvMzc1MjE5Njc4LWU5ZjAyOGNhLWU3MzAtNGQ5NC05MWY5LWEyNDBkNWFmMDBjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNTAwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGY1M2Q1ZmViOTFjMDIxNjUxNDgyNTJkMWExZGUyZTUxM2JkYzU2NDMwYWE1N2FmMWZlYmZiNDZmZTA4ZTQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3grxIYFjo6oeJpKzIIWULY0oZMgcmkax26SN-HTs9vs)

- 최신 product에 consumer DLT 설정 추가하여 재고 수량 부족에 토픽이 사라지지 않는 현상 해결
- 최신 product merge 후 테스트하기를 권장(api-communication 도 최신화해야됨)

주문 수량보다 재고 수량이 적을 경우 테스트 결과 
<img width="831" alt="image" src="https://github.com/user-attachments/assets/80944348-d6c8-4d03-a7df-6d8ef19e4d82">
