### ISSUE TITLE
[슬랙] 슬랙 api 개발 및 연동

### ISSUE THREAD

**Issue by bongdaehyun** [dev-wonny/coopang#121]
## TODO
* [x] api 명세서대로 api 구현
* [x] 슬랙과 연동
* [ ] 카프카 consumer 셋팅
## 예상 개발 기간
* 24.10.11 ~ 24.10.13 (3일)

**Comment by dev-wonny** [comment]
https://github.com/dev-wonny/coopang/pull/174 으로 대체됨
