### ISSUE TITLE
[부하테스트] 주문 생성 API 관련 부하테스트 진행

### ISSUE THREAD

**Issue by bongdaehyun** [dev-wonny/coopang#170]
## TODO
* [x] Jmeter로 성능테스트(쓰레드들의 수 100, Ramp-up 시간 1, 루프 카운트 10 으로 설정)
* [ ] 처리량은 200.0/sec 이상 이여야 하며 지연 시간을 최소화하도록 최적화
## 예상 개발 기간
* 24.10.22 ~ 24.10.23 (2일)

**Comment by bongdaehyun** [comment]
# 10.22일 부하테스트 진행결과

![Image](https://github.com/user-attachments/assets/112d9574-a6de-4403-8d29-50d41830f86b)

발제 요구사항 : 처리량은 200.0/sec 이상

## 해야될일 
1. 문제점 찾기(성능저하원인 분석) - 비관적 락때문에 성능이 저하될가능성 농후
2. 비관적 락의 범위를 줄이는 추후 쿼리 튜닝
3. 다른 락과 비교하여 성능테스트 진행(?)

**Comment by dev-wonny** [comment]
2024 10 25일자로 정리
