### ISSUE TITLE
[api-communication] 카프카 설정 및 메세지 설정하기

### ISSUE THREAD

**Issue by jiminchur** [dev-wonny/coopang#84]
## TODO
* [x] ProcessProduct
* [x] ProcessDelivery
* [x] ProcessPaymennt
* [x] ErrorProduct
* [x] ErrorPayment
* [x] CompleteProduct
* [x] CompletePayment
* [x] CompleteDelivery
* [x] RollbackProduct
* [x] CancelOrder
* [x] MessageToOrder
### 추가
* [x] CancelDelivery
* [x] ErrorCancelOrder
### Config
* [ ] ProducerConfig
* [ ] ConsumerConfig
## 예상 개발 기간
* 24.10.07 ~ 24.10.10 (3일)

**Comment by jiminchur** [comment]
## 10/07
* Kafka Config파일 재수정 후 merge하기

**Comment by jiminchur** [comment]
## 결제 취소시 필요한 Message
* Delivery쪽으로 결제 취소시 배송쪽에도 삭제하기 위함 또는 상태값 변경을 위한 전달이 필요함
* cancel_delivery로 추가할 예정
  * orderId만 담아서 보낼 예정

**Comment by jiminchur** [comment]
## 결제 취소시 실패했을 경우 Order쪽으로 보낼 Message
* Order쪽으로 PG사에게 결제 취소 요청을 보냈으나 결제 취소가 실패했을때 결제 취소를 재시도 하라는 Message를 보내기 위함
* error_cancel_order로 추가할 예정
  * orderId, errorMessage를 담을 예정

**Comment by jiminchur** [comment]
## 설계
### api-communication
* MessageProducer (interface)
![스크린샷 2024-10-14 오전 11 27 07](https://github.com/user-attachments/assets/fa7d4a36-82ab-4ac3-8c48-46f6baffb38d)

* MessageConsumer (interface)
* KafkaMessageProducerService
![스크린샷 2024-10-14 오전 11 27 28](https://github.com/user-attachments/assets/e32f3eda-66c7-469a-ae29-576dac84c1cf)
### 각 server 별
* KafkaMessageConsumerService
![스크린샷 2024-10-14 오전 11 28 54](https://github.com/user-attachments/assets/acdb390a-907f-4677-a82d-afc745a18eb5)

* 예시 ) OrderMessageService
![스크린샷 2024-10-14 오전 11 29 18](https://github.com/user-attachments/assets/66814253-23c3-40c8-b4a1-2121ef258051)

**Comment by dev-wonny** [comment]
https://github.com/dev-wonny/coopang/discussions/133#discussioncomment-10933554 여기 봐주세여
